### ISSUE TITLE
[Bug] Background color of AdminLayout different in screens

### ISSUE THREAD

**Issue by rm116** [creativetimofficial/paper-dashboard-react#11]
### Version
1.1.0
### Reproduction link
https://jsfiddle.net/
### Operating System
Windows 10
### Device
PC 
### Browser & Version
Google Chrome
### Steps to reproduce
1 - open a page in large screen : background color is White .
2- open a page in a small screen : background color in Brown or grey (background of the content ) from header to footer. not the menu.
### What is expected?
I want the same color in both screens, I want to fix it to White
### What is actually happening?
Color changing

---
### Additional comments
Thanks

**Comment by einazare** [comment]
Hello there, @rm116 ,

I've made some tests, and in my case, the color is the same (i.e. if I inspect the element, the css remains the same).
There is indeed a difference from my mobile phone to the Windows PC, but that difference is due to the screen settings.
Once again, the colors are the same, it is shown differently on different devices based on the device's screen settings.

Best,
Manu
