### ISSUE TITLE
Error: You should not use <Link> outside a <Router>

### ISSUE THREAD

**Issue by hitvoice** [creativetimofficial/paper-dashboard-react#3]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Browse without error.

# Current Behavior
When running `npm start` after `npm install`, in the browser it says:

> You should not use \<Link\> outside a \<Router\>
> ▶ 25 stack frames were collapsed.
> Module../src/index.js
> src/index.js:14
```
  11 | 
  12 | const hist = createBrowserHistory();
  13 | 
> 14 | ReactDOM.render(
  15 |   <Router history={hist}>
  16 |     <Switch>
  17 |       {indexRoutes.map((prop, key) => {
```

It seems to be something related to react router.

# Failure Information (for bugs)

> You should not use \<Link\> outside a \<Router\>

## Steps to Reproduce

1. Download, unzip, cd
2. npm install
3. npm start

## Context

* Device: Macbook Pro
* Operating System: MacOS Mojave 10.14.3
* Browser and Version: Chrome 72.0.3626.121

## Failure Logs

![image](https://user-images.githubusercontent.com/13765633/54491251-e81f5400-48f7-11e9-9294-95e9bf843f65.png)

**Comment by hitvoice** [comment]
Solve it by following https://github.com/creativetimofficial/material-dashboard-react/issues/87

**Comment by einazare** [comment]
Hello there, @hitvoice ,

Thank you for your interest in working with our products.
Sorry for the late response, we do not work on weekends.
In our package.json file we only install "react-router-dom". This package auto-installs "react-router". The problem is that is installing the latest version of "react-router", instead of the same version as "react-router-dom", and that is why you are having this error.
Run the following command:
```
npm i -E react-router@4.3.1
```
And this will do the trick.

Best,
Manu

**Comment by hitvoice** [comment]
It works. Thanks for the reply!
